
build_prod:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  only:
    - main
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker version
    - cd implementation/src/main/docker
    - printf "\nRUN ./mvnw package -Pprod verify jib:build -Djib.to.image=registry.gitlab.com/nfdi4culture/ta5-knowledge-graph/annotation-service:latest -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD" >> Dockerfile_PROD
    - docker build -t annotation_services_builder .


build_test:
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
  only:
    - test
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker version
    - cd implementation/src/main/docker
    - printf "\nRUN ./mvnw package -Pprod verify jib:build -Djib.to.image=registry.gitlab.com/nfdi4culture/ta5-knowledge-graph/annotation-service-dev:latest -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD" >> Dockerfile_TEST
    - docker build -t annotation_services_builder .