
build:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker version
    - ls -al
    - cd implementation/src/main/docker
    - ls -al
    - docker build -t annotation_services:testing .


