
build:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker version
    - cd implementation/src/main/docker
    # - ls -al
    # - cat Dockerfile
    - printf "\nRUN ./mvnw package -Pprod verify jib:build -Djib.to.image=registry.gitlab.com/nfdi4culture/ta5-knowledge-graph/annotation-service:latest -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD" >> Dockerfile
    # - cat Dockerfile


    - docker build -t annotation_services:testing .
    # - docker images -a

