
build:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker version
    # - git checkout jhipster-prototype
    - ls -al
    - cd implementation
    - ls -al
    - npm install