
build:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker version
    - ls -al
    - cd implementation
    - ls -al
    - npm install
    # - ./mvnw package -Pprod verify jib:dockerBuild


