variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''

services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ['--tls=false']

build_prod:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: jhipster/jhipster
  script:
    - mkdir tib-dev
    - cd tib-dev
    - mkdir annotationService
    # get latest project code from branch 'main'
    - git clone https://gitlab.com/nfdi4culture/ta5-knowledge-graph/annotation-service.git annotationService
    - cd annotationService
    - git checkout main
    # build project
    - npm i
    - npm ci --quiet
    # package docker container and push to gitlab container registry (PROD)
    - cd backend
    - ./mvnw -e --quiet package -Pprod verify jib:build -Djib.to.image=registry.gitlab.com/nfdi4culture/ta5-knowledge-graph/annotation-service:latest -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD

build_test:
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
  stage: deploy
  image: jhipster/jhipster
  script:
    - mkdir tib-dev
    - cd tib-dev
    - mkdir annotationService
    # get latest project code from branch 'main'
    - git clone https://gitlab.com/nfdi4culture/ta5-knowledge-graph/annotation-service.git annotationService
    - cd annotationService
    - git checkout test
    # build project
    - npm i
    - npm ci --quiet
    # package docker container and push to gitlab container registry (TEST)
    - cd backend
    - ./mvnw -e --quiet package -Pprod verify jib:build -Djib.to.image=registry.gitlab.com/nfdi4culture/ta5-knowledge-graph/annotation-service/test:latest -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD
