openapi: 3.0.1
info:
  title: annotationService
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile
paths:
<<<<<<< HEAD
  /status:
=======
  /annotation/status:
>>>>>>> 2e5545b139a65403936136a7357967bad22257fa
    get:
      summary: get the current status of the service
      description: ''
      operationId: getStatus
      responses:
        '200':
          description: Service is running
          content:
            text/plain:
              schema:
                type: string
                example: OK
             
        default:
          description: Unexpected error
<<<<<<< HEAD
  /annotation/wikidata:
    post:
      summary: >-
        retrieves a text and delivers a list of all recognized entities and
        relations within the wikiData knowlegdegraph as well as the
        corresponding class hierachy tree
      description: >-
        Uses Falcon2.0 Tool to retrieve entities and relations from wikidata.
        Adds the category hierarchy graph for these entities and relations,
        based on the "is subclass of" relation within wikiData
      operationId: getWikiDataAnnotation
=======
  /annotation/entities:
    post:
      summary: >-
        retrieves a text and delivers a list of all recognized entities and
        relations within the specified datasources as well as the
        corresponding class hierachy tree
      description: >-
        Uses the specified datasources to retrieve entities and relations.
        Adds the category hierarchy graph for these entities and relations.
      operationId: getEntities 
      
      parameters:
        - in: query
          name: wikidata
          required: false
          schema:
            type: boolean
          description: Optional parameter to include or exclude entities from wikidata
        - in: query
          name: wikidata_dbpedia
          schema:
            type: boolean
          description: Optional parameter to include or exclude entities from dbpedia
        - in: query
          name: iconclass
          schema:
            type: boolean
          description: Optional parameter to include or exclude entities(notations) from iconclass
>>>>>>> 2e5545b139a65403936136a7357967bad22257fa
      
      requestBody:
        description: Json array of text samples to annotate
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextArray'
      responses:
        '200':
          description: Annotations of the given post parameters
          content:
            application/json:
              schema:
                type: string  
                # $ref: '#/components/schemas/TextAnnotation'
        default:
          description: Generic error response
          
components:
  schemas:
    TextArray:
        type: array
        items:
          type: string
          example: 'Single entity name or fulltext'
          
    TextAnnotation:
      properties:
        entities:
          type: array
          items:
            type: array
            items:
              type: string
              example: ['Entity label', 'Wikidata URL']
              
        relations:
          type: array
          items:
            type: array
            items:
              type: string
              example: ['Relation label', 'Wikidata URL']
        hierarchy:
          type: array
          items:
            type: array
            items:
              type: string
              example: ['Subclass label', 'Parentclass label']

  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic
security:
  - jwt: []
  - basic: []
